name: 'CloudDrove Slack Notify'
description: 'This action will send a notification to Slack'
author: 'CloudDrove'
runs:
  using: 'docker'
  image: 'docker://clouddrove/slack-notify:1.2'
branding:
  icon: 'bell'
  color: 'yellow'
