name: 'CloudDrove Slack Notify'
description: 'This action will send a notification to Slack'
author: 'CloudDrove'
runs:
  using: 'docker'
  image: './Dockerfile'
branding:
  icon: 'bell'
  color: 'yellow'
