name: 'Slack Notification Action'
on:
  pull_request:
    branches:
      - master

jobs:
  Slack-action:
    name: 'Slack notification action'
    runs-on: ubuntu-latest
    steps:
      
      - name: 'Checkout'
        uses: actions/checkout@master

      - name: 'DockerHub login'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Docker image build'
        run: |
          docker build -t clouddrove/slack-notify:$TAG_VERSION .
        env:
          TAG_VERSION: 1.2

      - name: 'Docker Image push'
        run: |
          docker push clouddrove/slack-notify:$TAG_VERSION
        env:
          TAG_VERSION: 1.2

      - name: Slack Notification
        uses: ./
        env:
          SLACK_COLOR: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_TERRAFORM }}
